/** Shared vocabulary for the browser agent: observation, planning, action, result. */

export type Risk = "low" | "medium" | "high";

export type ActionKind = "click" | "fill" | "select" | "scroll" | "wait";

/**
 * One atomic, fully-specified action. Models choose between these; they never
 * produce selectors, coordinates, or code.
 */
export type BrowserAction = {
	id: string;
	kind: ActionKind;
	description: string;
	risk: Risk;
	ref?: string;
	value?: string;
	direction?: "down" | "up";
};

export type BrowserOption = {
	name: string;
	ref?: string;
};

export type BrowserElement = {
	/** Application-owned id. The only handle a model ever sees. */
	id: string;
	role: string;
	name: string;
	/** Nearest named ancestor, when the control has no accessible name itself. */
	context: string;
	value: string;
	states: string[];
	ref: string;
	canClick: boolean;
	canFill: boolean;
	options: BrowserOption[];
};

export type Observation = {
	/** Hash of the raw snapshot, used to detect stale decisions and real change. */
	fingerprint: string;
	text: string;
	elements: BrowserElement[];
	/** Open choice lists, summarised: a selection is normally expected next. */
	openLists: string[];
};

export type FactSource = "user" | "page" | "inference";

export type KnownFact = {
	name: string;
	value: string;
	source: FactSource;
	confidence: number;
};

/** Generic working memory. Generated by the reasoning model, never by the user. */
export type TaskState = {
	objective: string;
	knownFacts: KnownFact[];
	assumptions: string[];
	constraints: string[];
	unresolvedQuestions: { question: string; blocking: boolean }[];
	/** Planning horizon. The head is the current subgoal. */
	subgoals: string[];
	completedSubgoals: string[];
	successConditions: string[];
	risk: Risk;
};

export type Attempt = {
	subgoal: string;
	actionId: string;
	description: string;
	probability: number;
	confidence: number;
	stateChanged: boolean;
	result: string;
};

export type AgentStatus = "DONE" | "BLOCKED";

export type AgentResult = {
	status: AgentStatus;
	reason?: string;
	/** What the user should be told, written by the reasoning model. */
	summary: string;
	task: TaskState;
	attempts: Attempt[];
	/** Visible page text at the end of the run. */
	page: string;
	/** Set when the agent needs an answer it cannot safely assume. */
	question?: string;
	/** Where the time went, per phase and per step. */
	timings: string;
	/** Which model reasoned, and what the call contained. */
	planner?: string;
};

export type ProgressEvent = {
	step: number;
	message: string;
};
